### ISSUE TITLE
logistics pipes

### ISSUE THREAD

**Issue by 99dreada** [kaiheilos/Hydro#10]
so i might be way off the mark or missing something but isnt a straight pipe that also transfers signal missing from the store as im guessing from the lack of cable on the standard pipe that doesnt convey signal.

also im finding that the expected function of the pipes to turn on or off machines doesnt work on ram drills

**Comment by kaiheilos** [comment]
You were correct, it was missing. I've added it in the latest version (1.2a).

To turn the machines off, use a Valve pipe set to auto
