### ISSUE TITLE
Hydroneer Crash using Eternal Durability

### ISSUE THREAD

**Issue by skyros77** [kaiheilos/Hydro#3]
Just wanted to let you know that when I include the eternal durability pak it crashes Hydroneer.  The crash appears to happen when an item attempts to 'break'.  
000-EternalDuraCombo_P.pak

**Comment by raziel23x** [comment]
I am having the same issue as well and to help with debugging here is my save my crash report and my modpacks i have installed had to put them in zipfiles because github would not let me upload them
[UE4CC-Windows-69E5D8E44EDC48A8331DF9A3C7F8C405_0000.zip](https://github.com/kaiheilos/Hydro/files/4767762/UE4CC-Windows-69E5D8E44EDC48A8331DF9A3C7F8C405_0000.zip)
[Paks.zip](https://github.com/kaiheilos/Hydro/files/4767764/Paks.zip)
[HydroSave2.zip](https://github.com/kaiheilos/Hydro/files/4767766/HydroSave2.zip)

**Comment by raziel23x** [comment]
apparently it only crashes if you lock the drills in place as soon as i used the hammer and was able to pick them up again the crashing stopped

**Comment by skyros77** [comment]
AHH  ok let me try that

**Comment by skyros77** [comment]
So, unlocking the drills does fix the crash issue. However my drills/filters still break.  Not sure this mod works.  The unlimited dirt does though!

**Comment by skyros77** [comment]
Yea I'm pretty sure these mods don't work well.  I've tried the '000-EternalDuraCombo_P.pak' alone as well as the individual mods '000-EternalDrill_P.pak' and '000-MilWaterDura_P.pak'.  All of these crash unless your drills are unlocked, and none of them actually give any durability increase.  The unlimited dirt on the golliath does work however.

**Comment by raziel23x** [comment]
I am using a fresh game with them installed already so they are working as intended just that I am not able to lock the drills into place and have to pick them up and place them back down again at the start of each loading of the game or else they will crash the second they spit out the dirt

**Comment by jcardama** [comment]
I've managed to avoid crashing by pressing the unstuck button when I turn on the drills, then wait a few mins, and when I return to the drills they continue working without crashing, no unlocking required.

**Comment by skyros77** [comment]
@raziel23x so you have unlimited durability?

**Comment by raziel23x** [comment]
yep and when i load the save in the save editor all the items that have a durability are all set to 1000000

**Comment by kaiheilos** [comment]
> @raziel23x so you have unlimited durability?

The durability increase is only for newly built items, as the durability is stored in the save file. I'll be releasing an improved toolkit to allow the durability to be repaired, or remove the durability loss completely

**Comment by Lancekro** [comment]
I have managed to make the goliath drill work when locked in place by turning the water on first and then turn on the drills. 
But if my drill is on (lever up) when i turn the water on then the game crashes when the dirt spits out. i hope this helps you solve the problem.

**Comment by Navsigda** [comment]
> I have managed to make the goliath drill work when locked in place by turning the water on first and then turn on the drills.
> But if my drill is on (lever up) when i turn the water on then the game crashes when the dirt spits out. i hope this helps you solve the problem.

An interesting find on your part. It shouldn't be a factor though. The fact that it is, is rather perplexing. Neither locking nor its on/off state should have any affect on the drill paks. The durability float clamp and the durability itself are the only parameters affected. For the Goliath specifically, the voxel dirt is the only extra. 

Can you consistently reproduce the issue?

**Comment by Navsigda** [comment]
I've released version 2 of the mod earlier today. Please update to the latest version and check if the issue persists

**Comment by kaiheilos** [comment]
Anyone in here still having issues with this?

**Comment by raziel23x** [comment]
Mike1080p updated to the latest and on his latest youtube video said something about it still crashing and he was just using the combo and the daynight one
