### ISSUE TITLE
Eternal Drill

### ISSUE THREAD

**Issue by rtgs1967** [kaiheilos/Hydro#5]
I believe the Eternal drill pack isnt working, because the Goliath drills are destroying the dirt they are on.

**Comment by Navsigda** [comment]
> I believe the Eternal drill pack isnt working, because the Goliath drills are destroying the dirt they are on.

Are you placing new Goliath drills after the mod was installed?

**Comment by rtgs1967** [comment]
Yes, I've tried replacing the ones i had before i added the mod and I've tried fresh ones from the shop. I've also tried it on a fresh save

**Comment by rtgs1967** [comment]
With the release of the eternal dura combo v2 my problem is gone
