### ISSUE TITLE
000-EternalDuraComboV3.2_P.pak not working on latest steam version

### ISSUE THREAD

**Issue by Badonkadonk3** [kaiheilos/Hydro#6]
so as the title says i installed your mod and my Goliath still eats dirt.

**Comment by Carnaxus** [comment]
The latest Steam version hasn’t changed for quite a while.  Please list the mods you have installed; this sounds like a mod conflict to me.

**Comment by Badonkadonk3** [comment]
my other mods are, better crucible funnel, slower dirt, vehicle torque, larger wash pan and bucket.

**Comment by Badonkadonk3** [comment]
figured it out it was slower dirt.

**Comment by Carnaxus** [comment]
I’m not sure that’s the actual cause, since I’m running both without any issues, but hey, as long as it’s solved, right?
