### ISSUE TITLE
Conveyor Grinder

### ISSUE THREAD

**Issue by 99dreada** [kaiheilos/Hydro#8]
when placed ontop of belt it doesnt fucntion grider spins but doesnt cus gems

**Comment by Carnaxus** [comment]
Update your F7 menu, you may have an older version where it wasn’t functional yet.

**Comment by 99dreada** [comment]
amazing problem solved thank you i only downloaded it a couple of days ago so didnt expect it to be out of date

**Comment by Carnaxus** [comment]
Only a couple days?  It shouldn’t have been out of date; strange.  Oh well, it’s fixed, that’s what matters.  Right? :)
