### ISSUE TITLE
 000-Core-F7Menu_P.pak - Player wont move.

### ISSUE THREAD

**Issue by Claeman** [kaiheilos/Hydro#9]
I installed the Mod and at first it worked great.
Now when I use or even have the Mod in my Paks folder, my player won't move. He can jump but that is all.
I have tried to do unstuck. I have changed my keybindings for WASD. Nothing works.
If I quit the game and remove the Mod, everything is fine.
I have also tried deleting it and re-downloading it.

Anyone have any ideas???
Thanks,
Claeman

**Comment by ItchyBeard** [comment]
I had the same issue, load up the game, open F7 menu and make sure the acceleration is 2048 and the speed is 600

**Comment by Carnaxus** [comment]
That’s definitely an odd one.  If that setting’s default has somehow been changed, that could indeed be the problem; I’m far from the right person to ask for a more in-depth analysis though 😛

**Comment by kaiheilos** [comment]
Should be fixed in the latest version. Thanks for the report
